# Generated by Django 2.1 on 2018-08-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.PositiveIntegerField()),
                ('incident_datetime', models.DateTimeField(verbose_name='incident date')),
                ('division', models.CharField(max_length=200)),
                ('shift', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('arrested', models.CharField(blank=True, max_length=100)),
                ('officer', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-incident_datetime',),
            },
        ),
    ]
